// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:habit_loop/data/models/habit.dart';
import 'package:habit_loop/data/models/todo.dart';
import 'package:habit_loop/data/models/note.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(TodoAdapter());
    registerAdapter(NoteAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(TodoAdapter());
    registerAdapter(NoteAdapter());
  }
}
